const express = require('express');
const healthRoutes = require('./health');
const authRoutes = require('./auth');
const organizationRoutes = require('./organization');
const memberRoutes = require('./members');
const inviteRoutes = require('./invites');
const gmailRoutes = require('./gmail');
const contactRoutes = require('./contacts');
const productRoutes = require('./products');
const leadRoutes = require('./leads');
const quotationRoutes = require('./quotations');
const orderRoutes = require('./orders');
const importRoutes = require('./imports');
const exportRoutes = require('./exports');
const whatsappRoutes = require('./whatsapp');
const devRoutes = require('./dev');
const conversationRoutes = require('./conversations');
const quickReplyRoutes = require('./quickReplies');
const templateRoutes = require('./templates');
const leadSourceRoutes = require('./leadSources');
const { assignmentRoutes, autoReplyRoutes } = require('./routing');
const { taskRoutes, eventRoutes } = require('./workItems');
const ticketRoutes = require('./tickets');
const documentRoutes = require('./documents');
const campaignRoutes = require('./campaigns');
const { workflowRoutes, runRoutes, sequenceRoutes, enrollmentRoutes, notificationRoutes } = require('./automation');
const { faqRuleRoutes, botRoutes } = require('./bot');
const segmentRoutes = require('./segments');
const broadcastRoutes = require('./broadcasts');
const { settingsRoutes: paymentRoutes, linkRoutes: paymentLinkRoutes } = require('./payments');

const router = express.Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/organization', organizationRoutes);
router.use('/members', memberRoutes);
router.use('/invites', inviteRoutes);
router.use('/gmail', gmailRoutes);
router.use('/contacts', contactRoutes);
router.use('/products', productRoutes);
router.use('/leads', leadRoutes);
router.use('/quotations', quotationRoutes);
router.use('/pricing', quotationRoutes.pricingRouter);
router.use('/orders', orderRoutes);
router.use('/imports', importRoutes);
router.use('/exports', exportRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/dev', devRoutes);
router.use('/conversations', conversationRoutes);
router.use('/quick-replies', quickReplyRoutes);
router.use('/templates', templateRoutes);
router.use('/lead-sources', leadSourceRoutes);
router.use('/assignment-rules', assignmentRoutes);
router.use('/auto-reply-rules', autoReplyRoutes);
router.use('/tasks', taskRoutes);
router.use('/events', eventRoutes);
router.use('/tickets', ticketRoutes);
router.use('/documents', documentRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/workflows', workflowRoutes);
router.use('/automation-runs', runRoutes);
router.use('/sequences', sequenceRoutes);
router.use('/sequence-enrollments', enrollmentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/faq-rules', faqRuleRoutes);
router.use('/bot', botRoutes);
router.use('/segments', segmentRoutes);
router.use('/broadcasts', broadcastRoutes);
router.use('/payments', paymentRoutes);
router.use('/payment-links', paymentLinkRoutes);

module.exports = router;
